apiVersion: v1
kind: Namespace
metadata:
  name: my-cluster

---
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
spec:
  clusterIP: None
  selector:
    k8s-app: kube-dns
  ports:
  - name: dns
    port: 53
    protocol: UDP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system

---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
apiServer:
  certSANs:
  - "my-cluster.example.com"
networking:
  podSubnet: "10.244.0.0/16"

---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    node-labels: "node-role.kubernetes.io/master="
