---
- name: Configure Grafana and Prometheus
  hosts: all
  become: true
  tasks:
    - name: Add Grafana GPG Key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana Repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Start Grafana
      service:
        name: grafana-server
        state: started
        enabled: yes

    - name: Add Prometheus GPG Key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Prometheus Repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: prometheus

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Start Prometheus
      service:
        name: prometheus
        state: started
        enabled: yes
